# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('first_name', models.CharField(default=b'', max_length=255)),
                ('last_name', models.CharField(default=b'', max_length=255)),
                ('active_table_number', models.IntegerField(default=-1)),
                ('active_restaurant', models.CharField(default=b'', max_length=255)),
                ('address_table_combo', models.CharField(default=b'', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.IntegerField(default=-1)),
                ('order_name', models.CharField(default=b'', max_length=255)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customer_first_name', models.CharField(default=b'', max_length=255)),
                ('address_table_combo', models.CharField(default=b'', max_length=255)),
                ('table_number', models.IntegerField(default=-1)),
                ('restaurant_address', models.CharField(default=b'', max_length=255)),
                ('new_order', models.BooleanField(default=True)),
                ('active_order', models.BooleanField(default=True)),
                ('order_queued', models.BooleanField(default=False)),
                ('payment_pending', models.BooleanField(default=False)),
                ('receipt_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(default=-1)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('restaurant_name', models.CharField(default=b'', max_length=255)),
                ('restaurant_address', models.CharField(default=b'', max_length=255)),
                ('server_name', models.CharField(default=b'', max_length=255)),
                ('server_rating', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.IntegerField(default=-1)),
                ('server_id', models.IntegerField(default=-1)),
                ('party_size', models.IntegerField(default=1)),
                ('request_made', models.BooleanField(default=False)),
                ('time_of_request', models.IntegerField(default=-1)),
                ('is_finished', models.BooleanField(default=False)),
                ('time_of_finish', models.IntegerField(default=-1)),
                ('address_table_combo', models.CharField(default=b'', max_length=255, unique=True)),
                ('restaurant_name', models.CharField(default=b'', max_length=255)),
                ('new_table', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('time_created',),
            },
        ),
        migrations.CreateModel(
            name='TableRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_request', models.DateTimeField(auto_now_add=True)),
                ('address_table_combo', models.CharField(default=b'', max_length=255, unique=True)),
            ],
        ),
    ]
