# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='owner_id',
        ),
    ]
