# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0003_auto_20160131_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='server_name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
