# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0004_table_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='new_table',
            field=models.BooleanField(default=True),
        ),
    ]
