# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0006_myuser_active_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant_address',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
