# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_app', '0007_table_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='current_server_id',
            field=models.IntegerField(default=-1),
        ),
    ]
